from copy import deepcopy

import numpy as np

from ross.bearings.magnetic.amb_utils import get_ambs
from ross.bearings.magnetic.reduce_model import ReduceModel
from ross.bearings.magnetic.system_identification import (
    get_disturbance,
    SystemIdentification,
)


def simulate_with_optimal_x0(A, B, t_ref, i_ref, y_ref):
    """Simulate a state-space model using the shared initial-state solver.

    This wrapper preserves the import path used by the results module while
    keeping the implementation in :mod:`system_identification`.

    Parameters
    ----------
    A : np.ndarray
        State matrix of the discrete state-space model.
    B : np.ndarray
        Input matrix of the discrete state-space model.
    t_ref : array_like
        Reference time vector.
    i_ref : array_like
        Reference input signal, representing magnetic-bearing current.
    y_ref : array_like
        Reference output signal, representing displacement.

    Returns
    -------
    x_pred : np.ndarray
        Predicted state trajectory.
    x0_opt : np.ndarray
        Initial state estimate obtained by least squares.
    """
    from ross.bearings.magnetic.system_identification import (
        simulate_with_optimal_x0 as _simulate_with_optimal_x0,
    )

    return _simulate_with_optimal_x0(A, B, t_ref, i_ref, y_ref)


class AmbSystemIdentification:
    """Coordinate transfer-function identification for magnetic bearings.

    This class groups the data-driven identification and Hankel model
    reduction workflows used to obtain one model for each orthogonal direction
    of every magnetic bearing in a rotor.

    Parameters
    ----------
    rotor : ross.Rotor
        Rotor model containing one or more
        :class:`ross.MagneticBearingElement` objects.
    """

    def __init__(self, rotor):
        """Initialize the magnetic-bearing identification coordinator.

        Parameters
        ----------
        rotor : ross.Rotor
            Rotor model whose magnetic bearings will be identified or reduced.
        """
        self.rotor = rotor

    def run_amb_tf_identification(self, method, **kwargs):
        """Identify models for the rotor's magnetic-bearing directions.

        The ``"de"``, ``"slsqp"`` and ``"ss"`` methods generate disturbances,
        simulate the rotor time response, and identify a model from the
        resulting current and displacement signals.  ``"de"`` uses
        differential evolution, ``"slsqp"`` uses SLSQP optimization, and
        ``"ss"`` identifies a discrete state-space model through
        :class:`SystemIdentification`.  The ``"reduce"`` method builds a
        model directly from the rotor and reduces it using Hankel singular
        values instead of using simulated measurements.

        The returned result contains one model for each direction of every
        magnetic bearing.  Direction keys have the form
        ``"<bearing tag> (node <node>) - v"`` and
        ``"<bearing tag> (node <node>) - w"``.  For data-driven methods, the
        corresponding disturbance and reference data are also stored.  For
        ``"reduce"``, those entries are empty because no time-domain
        identification data are generated.

        Parameters
        ----------
        method : {"de", "slsqp", "ss", "reduce"}
            Identification method.  ``"de"``, ``"slsqp"`` and ``"ss"`` use
            data generated by time-response simulations.  ``"reduce"`` uses
            balanced Hankel model reduction.
        num_modes : int, optional
            Number of modes used in the modal reduction. For ``method="reduce"``,
            this is the number of modes retained in the reduced model. For the
            data-driven methods, it is the number of modes used by the time-response
            simulation. Default is 10.
        dt : float, optional
            Time step, in seconds, used to generate the disturbance and to
            simulate the rotor response.  Default is 1e-1.
        speed : float, optional
            Rotor speed, in rad/s, used by the time-response simulation.
            Default is 0.
        time_to_converge : float or None, optional
            Time, in seconds, before which simulated samples are discarded.
            Use ``None`` to retain the complete response.  Default is 1.0.

        Returns
        -------
        results : ross.AmbTfIdentificationResult
            Result object containing ``models``, ``perturbances``,
            ``ref_data``, and the selected ``method``.  The result also
            provides plotting methods for model responses, disturbances, and
            reference data.

        Examples
        --------
        >>> from ross.bearings.magnetic.amb_models import rotor_example_amb_simple
        >>> from ross.bearings.magnetic.amb_system_identification import (
        ...     AmbSystemIdentification,
        ... )
        >>> rotor = rotor_example_amb_simple()
        >>> identification = AmbSystemIdentification(rotor)
        >>> results = identification.run_amb_tf_identification(
        ...     "ss", dt=1e-3, speed=600.0, time_to_converge=1.0
        ... )
        >>> results.method
        'ss'
        >>> len(results.models) == 2 * len(
        ...     [b for b in rotor.bearing_elements
        ...      if b.__class__.__name__ == "MagneticBearingElement"]
        ... )
        True

        A reduced model can be generated by selecting the reduction method:

        >>> results = identification.run_amb_tf_identification(
        ...     "reduce", num_modes=10
        ... )
        >>> results.method
        'reduce'
        """

        from ross import AmbTfIdentificationResult

        valid_methods = {"de", "slsqp", "ss", "reduce"}
        if method not in valid_methods:
            raise ValueError(
                f"Unknown method '{method}'. Use 'de', 'slsqp', 'ss' or 'reduce'."
            )

        models = {}
        ref_data = {}
        disturbances = {}
        channel_names = None
        num_modes = kwargs.get("num_modes", 10)
        dt = kwargs.get("dt", 1e-1)
        speed = kwargs.get("speed", 0)
        time_to_converge = kwargs.get("time_to_converge", 1.0)

        if method in ["de", "slsqp", "ss"]:
            self._run_amb_tf_data_driven_identification(
                method,
                dt,
                speed,
                time_to_converge,
                num_modes,
                models,
                ref_data,
                disturbances,
            )

        elif method == "reduce":
            self._run_amb_tf_reduction_identification(
                num_modes=num_modes,
                models=models,
                ref_data=ref_data,
                disturbances=disturbances,
            )

            ambs = get_ambs(self.rotor)
            channel_names = [
                f"{amb.tag} - {axis}"
                for amb in ambs
                for axis in ("Current v", "Current w")
            ]

        return AmbTfIdentificationResult(
            models=models,
            perturbances=disturbances,
            ref_data=ref_data,
            method=method,
            channel_names=channel_names,
        )

    def _run_amb_tf_reduction_identification(
        self,
        num_modes,
        models,
        ref_data,
        disturbances,
    ):
        """Build and reduce one model for each magnetic-bearing direction.

        For every magnetic bearing in ``self.rotor``, this method creates a
        :class:`ReduceModel`, plots its Hankel singular values, and reduces the
        two orthogonal SISO models to the requested number of modes.  The resulting
        transfer functions are stored in ``models`` under ``- v`` and ``- w``
        keys.  Since this method performs model reduction rather than a
        time-domain experiment, it inserts empty disturbance arrays and empty
        reference-data arrays for each model.

        This is an internal helper called by
        :meth:`run_amb_tf_identification` when ``method="reduce"``.  The
        dictionaries passed as arguments are modified in place; the method has
        no explicit return value.

        Parameters
        ----------
        num_modes : int
            Number of modes retained in each reduced transfer-function model.
        models : dict
            Dictionary to receive the reduced models.  It is updated in place
            with the ``G_v`` and ``G_w`` models for every magnetic bearing.
        ref_data : dict
            Dictionary to receive empty ``current``, ``displacement``, and
            ``time`` arrays for every generated model.  It is updated in place.
        disturbances : dict
            Dictionary to receive an empty disturbance array for every
            generated model.  It is updated in place.

        Returns
        -------
        None
            The input dictionaries contain the generated models and metadata
            after the method completes.

        Examples
        --------
        >>> from ross.bearings.magnetic.amb_models import rotor_example_amb_simple
        >>> from ross.bearings.magnetic.amb_system_identification import (
        ...     AmbSystemIdentification,
        ... )
        >>> rotor = rotor_example_amb_simple()
        >>> identification = AmbSystemIdentification(rotor)
        >>> models, ref_data, disturbances = {}, {}, {}
        >>> identification._run_amb_tf_reduction_identification(
        ...     10, models, ref_data, disturbances
        ... )
        >>> len(models) == len(ref_data) == len(disturbances)
        True
        """
        original_model_builder = ReduceModel(
            rotor=deepcopy(self.rotor), speed=0, num_modes=-1
        )
        reduced_model_builder = ReduceModel(
            rotor=deepcopy(self.rotor), speed=0, num_modes=num_modes
        )

        original_model = original_model_builder.build_model()
        reduced_model = reduced_model_builder.build_model()

        models["reduced_model"] = reduced_model
        disturbances["reduced_model"] = []
        ref_data["reduced_model"] = {
            "current": [],
            "displacement": [],
            "time": [],
        }

        models["original_model"] = original_model
        disturbances["original_model"] = []
        ref_data["original_model"] = {
            "current": [],
            "displacement": [],
            "time": [],
        }

    def _run_amb_tf_data_driven_identification(
        self,
        method,
        dt,
        speed,
        time_to_converge,
        num_modes,
        models,
        ref_data,
        disturbances,
    ):
        """Identify magnetic-bearing models from simulated time-response data.

        The method generates a smooth, randomly stepped disturbance and applies
        it to each input direction of each magnetic bearing, one direction at
        a time.  For every experiment it runs :meth:`run_time_response`,
        extracts the magnetic-bearing current and displacement signals, and
        optionally removes the initial transient.  An
        :class:`SystemIdentification` instance then identifies the model
        using ``method``.

        Two entries are created for each magnetic bearing: one for the ``v``
        direction and one for the ``w`` direction.  The input dictionaries are
        modified in place.

        Parameters
        ----------
        method : {"de", "slsqp", "ss"}
            Data-driven identification algorithm passed to
            :meth:`SystemIdentification.identify`.
        dt : float
            Time step, in seconds, used for the generated disturbance and
            time-response simulation.
        speed : float
            Rotor speed, in rad/s, used by :meth:`run_time_response`.
        time_to_converge : float or None
            Time, in seconds, before which samples are discarded.  If
            ``None``, all generated samples are used.
        num_modes : int
            Number of modes used by the time-response simulation.
        models : dict
            Dictionary to populate with the identified models.  It is updated
            in place.
        ref_data : dict
            Dictionary to populate with the ``current``, ``displacement``, and
            ``time`` arrays for each identification experiment.  It is updated
            in place.
        disturbances : dict
            Dictionary to populate with the disturbance array for each
            identification experiment.  It is updated in place.

        Returns
        -------
        None
            The input dictionaries contain the generated models and metadata
            after the method completes.

        Examples
        --------
        >>> from ross.bearings.magnetic.amb_models import rotor_example_amb_simple
        >>> from ross.bearings.magnetic.amb_system_identification import (
        ...     AmbSystemIdentification,
        ... )
        >>> rotor = rotor_example_amb_simple()
        >>> identification = AmbSystemIdentification(rotor)
        >>> models, ref_data, disturbances = {}, {}, {}
        >>> identification._run_amb_tf_data_driven_identification(
        ...     "ss", 1e-3, 600.0, 1.0, 10, models, ref_data, disturbances
        ... )
        >>> len(models) == len(ref_data) == len(disturbances)
        True
        """
        ambs = get_ambs(self.rotor)
        n_ambs = len(ambs)

        for i in range(2 * n_ambs):
            t, d = get_disturbance(
                dt,
                changing_time=0.5,  # TODO: Deixar tudo isso a cargo do usuário
                steady_time=5,  # TODO: Deixar tudo isso a cargo do usuário
                n_steps=60,  # TODO: Deixar tudo isso a cargo do usuário
                step_amplitude=10e-6,  # TODO: Deixar tudo isso a cargo do usuário
            )

            d_v = np.zeros((len(t), 2 * n_ambs))
            d_v[:, i] = d

            F = np.zeros((t.size, self.rotor.ndof))

            response = self.rotor.run_time_response(
                speed,
                F,
                t,
                disturbance=d_v,
                weight=False,
                num_modes=num_modes,
            )

            current = response.I[:, i]
            disp = response.v_amb[:, i]

            if time_to_converge is not None:
                current = current[t >= time_to_converge]
                disp = disp[t >= time_to_converge]
                d = d[t >= time_to_converge]
                t = t[t >= time_to_converge]

            amb_system_identification = SystemIdentification(
                i_ref=current, y_ref=disp, t_ref=t
            )
            model = amb_system_identification.identify(method=method)

            mma = ambs[i // 2]
            if i % 2 == 0:
                models[f"{mma.tag} (node {mma.n}) - v"] = model
                disturbances[f"{mma.tag} (node {mma.n}) - v"] = d
                ref_data[f"{mma.tag} (node {mma.n}) - v"] = {
                    "current": current,
                    "displacement": disp,
                    "time": t,
                }
            else:
                models[f"{mma.tag} (node {mma.n}) - w"] = model
                disturbances[f"{mma.tag} (node {mma.n}) - w"] = d
                ref_data[f"{mma.tag} (node {mma.n}) - w"] = {
                    "current": current,
                    "displacement": disp,
                    "time": t,
                }
